#pragma once

#include <stdint.h>

enum VmsCsmTypedRecordId : uint8_t {
    VMS_CSM_RECORD_UNKNOWN = 0,
    VMS_CSM_RECORD_CAN_RX_RAW = 1,
    VMS_CSM_RECORD_CAN_TX_RAW = 2,
    VMS_CSM_RECORD_ENC_EDGE_RAW = 3,
    VMS_CSM_RECORD_ENC_DERIVED = 4,
    VMS_CSM_RECORD_ADC_SAMPLE = 5,
    VMS_CSM_RECORD_CONTROL_ACK = 6,
    VMS_CSM_RECORD_BOARD_EVENT = 7,
    VMS_CSM_RECORD_BOARD_HEALTH = 8,
    VMS_CSM_RECORD_CAPABILITY = 9,
    VMS_CSM_RECORD_HOST_CAN_TX_REQUEST = 10,
    VMS_CSM_RECORD_HOST_HEARTBEAT = 11,
    VMS_CSM_RECORD_HOST_CONTROL_SESSION = 12
};

enum VmsCsmControlAckStatus : uint8_t {
    VMS_CSM_CONTROL_REJECTED = 0,
    VMS_CSM_CONTROL_ACCEPTED = 1,
    VMS_CSM_CONTROL_ACCEPTED_WRITTEN = 2,
    VMS_CSM_CONTROL_ACCEPTED_RATE_LIMITED = 3
};

enum VmsCsmControlAckReason : uint8_t {
    VMS_CSM_CONTROL_REASON_OK = 0,
    VMS_CSM_CONTROL_REASON_BAD_LENGTH = 1,
    VMS_CSM_CONTROL_REASON_BAD_BUS = 2,
    VMS_CSM_CONTROL_REASON_UNSUPPORTED_FRAME = 3,
    VMS_CSM_CONTROL_REASON_DLC_OUT_OF_RANGE = 4,
    VMS_CSM_CONTROL_REASON_ID_NOT_ALLOWED = 5,
    VMS_CSM_CONTROL_REASON_CAN_NOT_READY = 6,
    VMS_CSM_CONTROL_REASON_CAN_WRITE_FAILED = 7,
    VMS_CSM_CONTROL_REASON_BAD_PROTOCOL = 8,
    VMS_CSM_CONTROL_REASON_SAFETY_NOT_ARMED = 9,
    VMS_CSM_CONTROL_REASON_HOST_TIMEOUT = 10,
    VMS_CSM_CONTROL_REASON_CONTROL_LEASE_EXPIRED = 11,
    VMS_CSM_CONTROL_REASON_SAFETY_LOCKOUT = 12,
    VMS_CSM_CONTROL_REASON_ESTOP_ASSERTED = 13,
    VMS_CSM_CONTROL_REASON_FIELD_POWER_LOST = 14,
    VMS_CSM_CONTROL_REASON_ENCODER_FAULT = 15,
    VMS_CSM_CONTROL_REASON_QUEUE_FULL = 16,
    VMS_CSM_CONTROL_REASON_TX_BUSY = 17,
    VMS_CSM_CONTROL_REASON_BUS_OFF = 18,
    VMS_CSM_CONTROL_REASON_ERROR_PASSIVE = 19,
    VMS_CSM_CONTROL_REASON_ROLE_UNRESOLVED = 20,
    VMS_CSM_CONTROL_REASON_POLICY_HASH_MISMATCH = 21,
    VMS_CSM_CONTROL_REASON_NEUTRAL_PROFILE_MISSING = 22,
    VMS_CSM_CONTROL_REASON_RATE_LIMITED = 23,
    VMS_CSM_CONTROL_REASON_UNSUPPORTED_COMMAND = 24
};

enum VmsCsmHostControlSessionAction : uint8_t {
    VMS_CSM_HOST_CONTROL_DISARM = 0,
    VMS_CSM_HOST_CONTROL_ARM = 1,
    VMS_CSM_HOST_CONTROL_RENEW_LEASE = 2,
    VMS_CSM_HOST_CONTROL_INSTALL_NEUTRAL_PROFILE = 3
};

enum VmsCsmSafetyState : uint8_t {
    VMS_CSM_SAFETY_BOOT = 0,
    VMS_CSM_SAFETY_MONITOR_ONLY = 1,
    VMS_CSM_SAFETY_READY = 2,
    VMS_CSM_SAFETY_ARMED = 3,
    VMS_CSM_SAFETY_CONTROL_ACTIVE = 4,
    VMS_CSM_SAFETY_HOST_TIMEOUT = 5,
    VMS_CSM_SAFETY_FAULT_LOCKOUT = 6,
    VMS_CSM_SAFETY_ESTOP = 7
};
